*CONTACT_TIED_SURFACE_TO_SURFACE_FAILURE_ID
$#     cid                                                                 title
         1                                                                      
$#   surfa     surfb  surfatyp  surfbtyp   saboxid   sbboxid      sapr      sbpr
         1         2         0         0         0         0         1         1
$#      fs        fd        dc        vc       vdc    penchk        bt        dt
      42.0       6.0       0.0    3.4641      60.0         0       0.01.00000E20
$#    sfsa      sfsb      sast      sbst     sfsat     sfsbt       fsf       vsf
       1.0       1.0       0.0       0.0       1.0       1.0       1.0       1.0
$#    soft    sofscl    lcidab    maxpar     sbopt     depth     bsort    frcfrq
         0       0.1         0     1.025         2         2         0         1